[options]
girs_directories = ["../gir-files"]
library = "Graphene"
version = "1.0"
min_cfg_version = "1.10"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true
trust_return_value_nullability = true

generate = [
    "Graphene.EulerOrder",
    "Graphene.RayIntersectionKind",
]

[[object]]
name = "Graphene.*"
status = "generate"
    [[object.constant]]
    name = "SIMD_S"
    ignore = true

[[object]]
name = "Graphene.Box"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true
    [[object.function]]
    name = "get_vertices"
    # float array
    manual = true

[[object]]
name = "Graphene.Euler"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Frustum"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true
    [[object.function]]
    name = "get_planes"
    # float array
    manual = true

[[object]]
name = "Graphene.Matrix"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true
    [[object.function]]
    name = "to_float"
    # float array
    manual = true

[[object]]
name = "Graphene.Plane"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Point"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Point3D"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Quad"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true
    [[object.function]]
    name = "get_point"
    # needs bounds check
    manual = true

[[object]]
name = "Graphene.Quaternion"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Ray"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Rect"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true
    [[object.function]]
    name = "get_vertices"
    # float array
    manual = true
    [[object.function]]
    name = "inset"
        [object.function.return]
        type = "none"
    [[object.function]]
    name = "normalize"
        [object.function.return]
        type = "none"
    [[object.function]]
    name = "offset"
        [object.function.return]
        type = "none"

[[object]]
# missing memory management functions
name = "Graphene.Simd4F"
status = "ignore"

[[object]]
# missing memory management functions
name = "Graphene.Simd4X4F"
status = "ignore"

[[object]]
name = "Graphene.Size"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Sphere"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Triangle"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true

[[object]]
name = "Graphene.Vec2"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true
    [[object.function]]
    name = "to_float"
    # float array
    manual = true

[[object]]
name = "Graphene.Vec3"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true
    [[object.function]]
    name = "to_float"
    # float array
    manual = true

[[object]]
name = "Graphene.Vec4"
status = "generate"
boxed_inline = true
    [[object.derive]]
    name = "Debug"

    [[object.function]]
    # contents undefined
    name = "alloc"
    ignore = true
    [[object.function]]
    pattern = "init.*"
    # manual proper constructor
    manual = true
    [[object.function]]
    name = "to_float"
    # float array
    manual = true
