[options]
work_mode = "sys"
library = "GObject"
version = "2.0"
min_cfg_version = "2.56"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
]

ignore = [
    "GObject.VaClosureMarshal",
    "GObject.SignalCVaMarshaller",
]

[[object]]
name = "GObject.SignalGroup"
status = "generate"
    [[object.function]]
    name = "connect_closure"
    # https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/332
    version = "2.74"
